/**
 * Generates the canonical RNG vectors used by the TypeScript tests and by the
 * Solidity tests (`Shuffle.sol` must reproduce them byte for byte).
 *
 * Run with: `npm run vectors` (regenerating is a deliberate act — the JSON is
 * committed so both sides of the stack are pinned to the same bytes).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bytesToHex, commitmentFor, entropyFrom, shuffleDeck } from '../packages/shared/src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../packages/shared/vectors/rng-vectors.json');

interface RngVector {
  name: string;
  note: string;
  deckSeed: string;
  nonce: string;
  commitment: string;
  anchorBlockHash: string;
  entropy: string;
  deck: number[];
  wordsConsumed: number;
  drawsConsumed: number;
}

const hex = (byte: number, length = 32): string => `0x${byte.toString(16).padStart(2, '0').repeat(length)}`;

const cases: { name: string; note: string; deckSeed: string; nonce: string; anchor: string }[] = [
  {
    name: 'vector-1',
    note: 'sequential seed bytes 0x00..0x1f, nonce 1, anchor all-zero',
    deckSeed: `0x${Array.from({ length: 32 }, (_, i) => i.toString(16).padStart(2, '0')).join('')}`,
    nonce: '1',
    anchor: hex(0),
  },
  {
    name: 'vector-2',
    note: 'all-zero seed (degenerate), nonce 0, anchor 0xff..ff',
    deckSeed: hex(0),
    nonce: '0',
    anchor: hex(0xff),
  },
  {
    name: 'vector-3',
    note: 'all-0xff seed, large nonce near uint64 max, sequential anchor',
    deckSeed: hex(0xff),
    nonce: '18446744073709551615',
    anchor: `0x${Array.from({ length: 32 }, (_, i) => ((i * 7 + 3) % 256).toString(16).padStart(2, '0')).join('')}`,
  },
  {
    name: 'vector-4',
    note: 'mainnet-shaped anchor hash, nonce 42',
    deckSeed: `0x${Array.from({ length: 32 }, (_, i) => ((i * 31 + 17) % 256).toString(16).padStart(2, '0')).join('')}`,
    nonce: '42',
    anchor: '0x9f2d1b4c7e6a8d0f3b5c9a1e2d4f6078aabbccddeeff00112233445566778899',
  },
  {
    name: 'vector-5',
    note: 'uint256-max nonce (abi.encodePacked width check)',
    deckSeed: `0x${Array.from({ length: 32 }, (_, i) => ((255 - i) % 256).toString(16).padStart(2, '0')).join('')}`,
    nonce: (2n ** 256n - 1n).toString(),
    anchor: hex(0x5a),
  },
  {
    name: 'vector-6',
    note: 'ascii seed "llmpoker", nonce 4663 (chain id), anchor 0x00..0x1f',
    deckSeed: bytesToHex(new TextEncoder().encode('llmpoker'.padEnd(32, '!'))),
    nonce: '4663',
    anchor: `0x${Array.from({ length: 32 }, (_, i) => i.toString(16).padStart(2, '0')).join('')}`,
  },
];

const vectors: RngVector[] = cases.map((c) => {
  const seed = c.deckSeed;
  const anchor = c.anchor;
  const commitment = `0x${bytesToHex(commitmentFor(seed, BigInt(c.nonce)))}`;
  const entropyBytes = entropyFrom(seed, anchor);
  const entropy = `0x${bytesToHex(entropyBytes)}`;
  const shuffle = shuffleDeck(entropyBytes);
  return {
    name: c.name,
    note: c.note,
    deckSeed: seed,
    nonce: c.nonce,
    commitment,
    anchorBlockHash: anchor,
    entropy,
    deck: shuffle.deck,
    wordsConsumed: shuffle.wordsConsumed,
    drawsConsumed: shuffle.drawsConsumed,
  };
});

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `${JSON.stringify(
    {
      $comment:
        'Generated by scripts/gen-rng-vectors.ts. DO NOT EDIT BY HAND. Shuffle.sol, the engine and the verifier must all reproduce these decks.',
      algorithm: 'keccak256 counter-mode Fisher-Yates, rejection sampled over uint64 draws',
      generatedFrom: 'packages/shared/src/rng.ts',
      vectors,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

console.log(`wrote ${vectors.length} vectors to ${outFile}`);
for (const v of vectors) {
  console.log(`${v.name}: entropy=${v.entropy.slice(0, 18)}… first8=[${v.deck.slice(0, 8).join(',')}] words=${v.wordsConsumed}`);
}
