/**
 * Generates the canonical FR-6.2/6.3 Merkle vectors, shared by the TypeScript
 * tests and the Solidity suite (`contracts/test/Shuffle.merkle.test.ts`).
 *
 * The RNG vectors pin the *shuffle*; these pin the *commitment layer*: the leaf
 * encoding, the ordered interior rule, the 64-leaf padding, the root, the
 * six-hash inclusion proofs, and the composition `entropy → deck → leaves →
 * root` that FR-6.2 actually commits to.
 *
 * The `orderSensitivity` pair is deliberate: two decks with the *same multiset*
 * of cards in a different sequence must have different roots. A sorted-pair
 * interior rule would give them the same root, i.e. commit to the deck's set
 * rather than its sequence, which is a silent, total loss of fairness.
 *
 * Run with: `npm run vectors`.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  bytesToHex,
  bytesToHex32,
  commitDeckOrder,
  entropyFrom,
  keccak256Concat,
  merkleProof,
  shuffleDeck,
  uint256ToBytes,
  utf8ToBytes,
} from '../packages/shared/src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../packages/shared/vectors/merkle-vectors.json');

const PROOF_INDICES = [0, 1, 25, 45, 51];
const VECTOR_COUNT = 5;

interface MerkleVector {
  name: string;
  note: string;
  deckSeed: string;
  anchorBlockHash: string;
  entropy: string;
  deck: number[];
  salts: string[];
  leaves: string[];
  root: string;
  proofs: Record<string, string[]>;
}

const derive = (label: string, index: number): Uint8Array =>
  keccak256Concat([utf8ToBytes(label), uint256ToBytes(index)]);

/** Deterministic, obviously-not-random salt: `keccak256("merkle-salt" ‖ vector ‖ position)`. */
const saltFor = (vectorIndex: number, position: number): Uint8Array =>
  keccak256Concat([utf8ToBytes('merkle-salt'), uint256ToBytes(vectorIndex), uint256ToBytes(position)]);

function buildVector(index: number): MerkleVector {
  const seed = derive('merkle-seed', index);
  const anchor = derive('merkle-anchor', index);
  const entropy = entropyFrom(seed, anchor);
  const deck = shuffleDeck(entropy).deck;
  const salts = Array.from({ length: 52 }, (_, position) => saltFor(index, position));
  const commitment = commitDeckOrder(deck, salts);
  const proofs: Record<string, string[]> = {};
  for (const position of PROOF_INDICES) {
    proofs[String(position)] = merkleProof(commitment.leaves, position).map(bytesToHex32);
  }
  return {
    name: `merkle-${index + 1}`,
    note: `entropy-derived deck from deckSeed/anchor pair ${index + 1}`,
    deckSeed: bytesToHex32(seed),
    anchorBlockHash: bytesToHex32(anchor),
    entropy: bytesToHex32(entropy),
    deck,
    salts: salts.map(bytesToHex32),
    leaves: commitment.leaves.map(bytesToHex32),
    root: bytesToHex32(commitment.root),
    proofs,
  };
}

const vectors: MerkleVector[] = Array.from({ length: VECTOR_COUNT }, (_, i) => buildVector(i));

// Two decks with the same cards in a different sequence: the roots MUST differ.
const base = vectors[0]!;
const swappedDeck = [...base.deck];
const tmp = swappedDeck[0]!;
swappedDeck[0] = swappedDeck[1]!;
swappedDeck[1] = tmp;
const swappedSalts = base.salts.map((s) => s);
const swapped = commitDeckOrder(swappedDeck, swappedSalts);

const orderSensitivity = {
  note: 'same 52-card multiset, positions 0 and 1 transposed: the roots must differ, proving the tree commits to the sequence and not the set',
  deckA: base.deck,
  saltsA: base.salts,
  rootA: base.root,
  deckB: swappedDeck,
  saltsB: swappedSalts,
  rootB: bytesToHex32(swapped.root),
};

if (orderSensitivity.rootA === orderSensitivity.rootB) {
  throw new Error('order sensitivity violated: transposing two deck positions left the root unchanged');
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `${JSON.stringify(
    {
      $comment:
        'Generated by scripts/gen-merkle-vectors.ts. DO NOT EDIT BY HAND. Shuffle.sol and packages/shared must both reproduce these roots, leaves and proofs.',
      encoding: {
        leaf: 'keccak256(abi.encodePacked(uint8 card, bytes32 salt))',
        inner: 'keccak256(abi.encode(bytes32 left, bytes32 right))  // ORDERED, never sorted',
        shape: '52 leaves padded with ZERO_LEAF = keccak256(abi.encode(uint256(0))) to 64',
        proofLength: 6,
      },
      generatedFrom: 'packages/shared/src/merkle.ts',
      vectors,
      orderSensitivity,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

console.log(`wrote ${vectors.length} Merkle vectors to ${outFile}`);
for (const v of vectors) {
  console.log(`${v.name}: root=${v.root.slice(0, 18)}… first4deck=[${v.deck.slice(0, 4).join(',')}]`);
}
console.log(`order sensitivity: rootA=${orderSensitivity.rootA.slice(0, 18)}… rootB=${orderSensitivity.rootB.slice(0, 18)}… (differ)`);
console.log(`indices with proofs: ${PROOF_INDICES.join(', ')}`);
void bytesToHex;
